# Generated by Django 4.2.5 on 2023-09-26 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_column='user_id', null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('key', models.CharField(blank=True, db_column='key', max_length=32)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 26, 15, 10, 18, 237873))),
            ],
            options={
                'db_table': 'reset_password',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 15, 10, 18, 236869)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 15, 10, 18, 235869)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 15, 10, 18, 233835)),
        ),
    ]
